### ISSUE TITLE
Scala 2.11 cannot resolve dependencies

### ISSUE THREAD

**Issue by LiuxyEric** [SETL-Developers/setl#172]
sbt file: "com.jcdecaux.setl" %% "setl" % "1.0.0-SNAPSHOT"
result:
![image](https://user-images.githubusercontent.com/28945845/103390161-d9964100-4b4d-11eb-89ce-ddb0d6935d51.png)

**Comment by qxzzxq** [comment]
Hey @LiuxyEric, what are your Spark and Scala versions? Spark 3.0 may not work with Scala 2.11.

If it's possible, try Spark 3.0 with Scala 2.12

**Comment by LiuxyEric** [comment]
I am using Spark 2.4 and Scala 2.11. It seems that the three dependencies I mentioned on the picture don't have the right version for scala 2.11.  I updated my scala version to 2.12 and the problem solved. Thanks for you replay!

**Comment by qxzzxq** [comment]
Otherwise, another temporary fix is to manually import these three dependencies with the following versions in the sbt file when  it's not possible to upgrade from scala 2.11 to 2.12 😄 

```xml
<dependency>
    <groupId>com.audienceproject</groupId>
    <artifactId>spark-dynamodb_2.11</artifactId>
    <version>1.0.4</version>
</dependency>
<dependency>
    <groupId>io.delta</groupId>
    <artifactId>delta-core_2.11</artifactId>
    <version>0.6.1</version>
</dependency>
<dependency>
    <groupId>com.datastax.spark</groupId>
    <artifactId>spark-cassandra-connector_2.11</artifactId>
    <version>2.5.1</version>
</dependency>
```

I've added this into the project's readme.

There is indeed something to be improved with the project's pom file and the CI script. I have opened a new issue to continue tracking this problem #173 .
